name: CICD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build docker image
        run: docker build -t umakeshava/API .
      - name: Publish image to docker hub
        run: docker push umakeshava/API:latest
